# Generated by Django 2.1.1 on 2022-08-14 14:42

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220814_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='year_in_school',
            new_name='region',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='guest@kt.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='langlat',
            field=models.CharField(blank=True, help_text='위경도를 입력해주세요', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
