# Generated by Django 2.1.1 on 2022-08-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
