# Generated by Django 2.1.1 on 2022-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ip',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
